/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as CountriesCountryCodeImport } from "./routes/countries.$countryCode";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const CountriesCountryCodeRoute = CountriesCountryCodeImport.update({
  path: "/countries/$countryCode",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/countries/$countryCode": {
      id: "/countries/$countryCode";
      path: "/countries/$countryCode";
      fullPath: "/countries/$countryCode";
      preLoaderRoute: typeof CountriesCountryCodeImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/countries/$countryCode": typeof CountriesCountryCodeRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/countries/$countryCode": typeof CountriesCountryCodeRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/countries/$countryCode": typeof CountriesCountryCodeRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/countries/$countryCode";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/countries/$countryCode";
  id: "__root__" | "/" | "/countries/$countryCode";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CountriesCountryCodeRoute: typeof CountriesCountryCodeRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesCountryCodeRoute: CountriesCountryCodeRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/countries/$countryCode"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/countries/$countryCode": {
      "filePath": "countries.$countryCode.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
