/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CountriesCountryNameImport } from './routes/countries.$countryName'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CountriesCountryNameRoute = CountriesCountryNameImport.update({
  path: '/countries/$countryName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/countries/$countryName': {
      id: '/countries/$countryName'
      path: '/countries/$countryName'
      fullPath: '/countries/$countryName'
      preLoaderRoute: typeof CountriesCountryNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries/$countryName': typeof CountriesCountryNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countries/$countryName': typeof CountriesCountryNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/countries/$countryName': typeof CountriesCountryNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/countries/$countryName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/countries/$countryName'
  id: '__root__' | '/' | '/countries/$countryName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesCountryNameRoute: typeof CountriesCountryNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesCountryNameRoute: CountriesCountryNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/countries/$countryName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/countries/$countryName": {
      "filePath": "countries.$countryName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
